//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Mio;

/**
 * Servicio para consultar información del grafo completo
 **/
public interface GraphService extends com.zeroc.Ice.Object
{
    /**
     * Obtiene todas las paradas del sistema
     * @param current The Current object for the invocation.
     **/
    Stop[] getAllStops(com.zeroc.Ice.Current current);

    /**
     * Obtiene todos los arcos del sistema
     * @param current The Current object for the invocation.
     **/
    Arc[] getAllArcs(com.zeroc.Ice.Current current);

    /**
     * Obtiene todos los arcos agrupados por ruta y orientación
     * Retorna un mapa de arcos organizados
     * @param current The Current object for the invocation.
     **/
    Arc[] getArcsByRouteAndOrientation(com.zeroc.Ice.Current current);

    /**
     * Obtiene estadísticas del grafo
     * Retorna: [numRoutes, numStops, numArcs, numArcsOrientation0, numArcsOrientation1]
     * @param current The Current object for the invocation.
     **/
    int[] getGraphStatistics(com.zeroc.Ice.Current current);

    /**
     * Imprime en consola del servidor el listado completo de arcos
     * organizados por ruta y orientación
     * @param current The Current object for the invocation.
     **/
    void printArcsToConsole(com.zeroc.Ice.Current current);

    /**
     * Encuentra la ruta más corta entre dos paradas
     * @param originStopId ID de la parada de origen
     * @param destStopId ID de la parada de destino
     * @param current The Current object for the invocation.
     * @return RouteResult con la ruta encontrada o información de error
     **/
    RouteResult findRoute(int originStopId, int destStopId, com.zeroc.Ice.Current current)
        throws StopNotFoundException;

    /**
     * Obtiene todas las paradas alcanzables desde una parada de origen
     * @param originStopId ID de la parada de origen
     * @param current The Current object for the invocation.
     * @return IntList con los IDs de las paradas alcanzables
     **/
    int[] getReachableStops(int originStopId, com.zeroc.Ice.Current current)
        throws StopNotFoundException;

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::Mio::GraphService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::Mio::GraphService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAllStops(GraphService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        Stop[] ret = obj.getAllStops(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        StopListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAllArcs(GraphService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        Arc[] ret = obj.getAllArcs(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getArcsByRouteAndOrientation(GraphService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        Arc[] ret = obj.getArcsByRouteAndOrientation(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getGraphStatistics(GraphService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        int[] ret = obj.getGraphStatistics(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeIntSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_printArcsToConsole(GraphService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        obj.printArcsToConsole(current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_findRoute(GraphService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_originStopId;
        int iceP_destStopId;
        iceP_originStopId = istr.readInt();
        iceP_destStopId = istr.readInt();
        inS.endReadParams();
        RouteResult ret = obj.findRoute(iceP_originStopId, iceP_destStopId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        RouteResult.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getReachableStops(GraphService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_originStopId;
        iceP_originStopId = istr.readInt();
        inS.endReadParams();
        int[] ret = obj.getReachableStops(iceP_originStopId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeIntSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "findRoute",
        "getAllArcs",
        "getAllStops",
        "getArcsByRouteAndOrientation",
        "getGraphStatistics",
        "getReachableStops",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "printArcsToConsole"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_findRoute(this, in, current);
            }
            case 1:
            {
                return _iceD_getAllArcs(this, in, current);
            }
            case 2:
            {
                return _iceD_getAllStops(this, in, current);
            }
            case 3:
            {
                return _iceD_getArcsByRouteAndOrientation(this, in, current);
            }
            case 4:
            {
                return _iceD_getGraphStatistics(this, in, current);
            }
            case 5:
            {
                return _iceD_getReachableStops(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 9:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 10:
            {
                return _iceD_printArcsToConsole(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
