//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Mio;

public class LineNotFoundException extends com.zeroc.Ice.UserException
{
    public LineNotFoundException()
    {
        this.message = "";
    }

    public LineNotFoundException(Throwable cause)
    {
        super(cause);
        this.message = "";
    }

    public LineNotFoundException(int lineId, String message)
    {
        this.lineId = lineId;
        this.message = message;
    }

    public LineNotFoundException(int lineId, String message, Throwable cause)
    {
        super(cause);
        this.lineId = lineId;
        this.message = message;
    }

    public String ice_id()
    {
        return "::Mio::LineNotFoundException";
    }

    public int lineId;

    public String message;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Mio::LineNotFoundException", -1, true);
        ostr_.writeInt(lineId);
        ostr_.writeString(message);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        lineId = istr_.readInt();
        message = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -906390427942996110L;
}
