//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Mio;

/**
 * Servicio para consultar información de rutas
 **/
public interface RouteServicePrx extends com.zeroc.Ice.ObjectPrx
{
    /**
     * Obtiene todas las rutas disponibles
     **/
    default Line[] getAllLines()
    {
        return getAllLines(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene todas las rutas disponibles
     * @param context The Context map to send with the invocation.
     **/
    default Line[] getAllLines(java.util.Map<String, String> context)
    {
        return _iceI_getAllLinesAsync(context, true).waitForResponse();
    }

    /**
     * Obtiene todas las rutas disponibles
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Line[]> getAllLinesAsync()
    {
        return _iceI_getAllLinesAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene todas las rutas disponibles
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Line[]> getAllLinesAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllLinesAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Line[]> _iceI_getAllLinesAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Line[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAllLines", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Line[] ret;
                     ret = LineListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Obtiene una ruta específica por ID
     **/
    default Line getLineById(int lineId)
        throws LineNotFoundException
    {
        return getLineById(lineId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene una ruta específica por ID
     * @param context The Context map to send with the invocation.
     **/
    default Line getLineById(int lineId, java.util.Map<String, String> context)
        throws LineNotFoundException
    {
        try
        {
            return _iceI_getLineByIdAsync(lineId, context, true).waitForResponseOrUserEx();
        }
        catch(LineNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    /**
     * Obtiene una ruta específica por ID
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Line> getLineByIdAsync(int lineId)
    {
        return _iceI_getLineByIdAsync(lineId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene una ruta específica por ID
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Line> getLineByIdAsync(int lineId, java.util.Map<String, String> context)
    {
        return _iceI_getLineByIdAsync(lineId, context, false);
    }

    /**
     * @hidden
     * @param iceP_lineId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Line> _iceI_getLineByIdAsync(int iceP_lineId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Line> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getLineById", null, sync, _iceE_getLineById);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_lineId);
                 }, istr -> {
                     Line ret;
                     ret = Line.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getLineById =
    {
        LineNotFoundException.class
    };

    /**
     * Obtiene todas las paradas de una ruta específica
     * @param lineId ID de la ruta
     * @param orientation 0=ida, 1=regreso
     **/
    default Stop[] getStopsByLine(int lineId, int orientation)
        throws InvalidOrientationException,
               LineNotFoundException
    {
        return getStopsByLine(lineId, orientation, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene todas las paradas de una ruta específica
     * @param lineId ID de la ruta
     * @param orientation 0=ida, 1=regreso
     * @param context The Context map to send with the invocation.
     **/
    default Stop[] getStopsByLine(int lineId, int orientation, java.util.Map<String, String> context)
        throws InvalidOrientationException,
               LineNotFoundException
    {
        try
        {
            return _iceI_getStopsByLineAsync(lineId, orientation, context, true).waitForResponseOrUserEx();
        }
        catch(InvalidOrientationException ex)
        {
            throw ex;
        }
        catch(LineNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    /**
     * Obtiene todas las paradas de una ruta específica
     * @param lineId ID de la ruta
     * @param orientation 0=ida, 1=regreso
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Stop[]> getStopsByLineAsync(int lineId, int orientation)
    {
        return _iceI_getStopsByLineAsync(lineId, orientation, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene todas las paradas de una ruta específica
     * @param lineId ID de la ruta
     * @param orientation 0=ida, 1=regreso
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Stop[]> getStopsByLineAsync(int lineId, int orientation, java.util.Map<String, String> context)
    {
        return _iceI_getStopsByLineAsync(lineId, orientation, context, false);
    }

    /**
     * @hidden
     * @param iceP_lineId -
     * @param iceP_orientation -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Stop[]> _iceI_getStopsByLineAsync(int iceP_lineId, int iceP_orientation, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Stop[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getStopsByLine", null, sync, _iceE_getStopsByLine);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_lineId);
                     ostr.writeInt(iceP_orientation);
                 }, istr -> {
                     Stop[] ret;
                     ret = StopListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getStopsByLine =
    {
        InvalidOrientationException.class,
        LineNotFoundException.class
    };

    /**
     * Obtiene los arcos de una ruta específica
     * @param lineId ID de la ruta
     * @param orientation 0=ida, 1=regreso
     **/
    default Arc[] getArcsByLine(int lineId, int orientation)
        throws InvalidOrientationException,
               LineNotFoundException
    {
        return getArcsByLine(lineId, orientation, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene los arcos de una ruta específica
     * @param lineId ID de la ruta
     * @param orientation 0=ida, 1=regreso
     * @param context The Context map to send with the invocation.
     **/
    default Arc[] getArcsByLine(int lineId, int orientation, java.util.Map<String, String> context)
        throws InvalidOrientationException,
               LineNotFoundException
    {
        try
        {
            return _iceI_getArcsByLineAsync(lineId, orientation, context, true).waitForResponseOrUserEx();
        }
        catch(InvalidOrientationException ex)
        {
            throw ex;
        }
        catch(LineNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    /**
     * Obtiene los arcos de una ruta específica
     * @param lineId ID de la ruta
     * @param orientation 0=ida, 1=regreso
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Arc[]> getArcsByLineAsync(int lineId, int orientation)
    {
        return _iceI_getArcsByLineAsync(lineId, orientation, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene los arcos de una ruta específica
     * @param lineId ID de la ruta
     * @param orientation 0=ida, 1=regreso
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Arc[]> getArcsByLineAsync(int lineId, int orientation, java.util.Map<String, String> context)
    {
        return _iceI_getArcsByLineAsync(lineId, orientation, context, false);
    }

    /**
     * @hidden
     * @param iceP_lineId -
     * @param iceP_orientation -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Arc[]> _iceI_getArcsByLineAsync(int iceP_lineId, int iceP_orientation, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Arc[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getArcsByLine", null, sync, _iceE_getArcsByLine);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_lineId);
                     ostr.writeInt(iceP_orientation);
                 }, istr -> {
                     Arc[] ret;
                     ret = ArcListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getArcsByLine =
    {
        InvalidOrientationException.class,
        LineNotFoundException.class
    };

    /**
     * Obtiene información de una parada específica
     **/
    default Stop getStopById(int stopId)
        throws StopNotFoundException
    {
        return getStopById(stopId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene información de una parada específica
     * @param context The Context map to send with the invocation.
     **/
    default Stop getStopById(int stopId, java.util.Map<String, String> context)
        throws StopNotFoundException
    {
        try
        {
            return _iceI_getStopByIdAsync(stopId, context, true).waitForResponseOrUserEx();
        }
        catch(StopNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    /**
     * Obtiene información de una parada específica
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Stop> getStopByIdAsync(int stopId)
    {
        return _iceI_getStopByIdAsync(stopId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene información de una parada específica
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Stop> getStopByIdAsync(int stopId, java.util.Map<String, String> context)
    {
        return _iceI_getStopByIdAsync(stopId, context, false);
    }

    /**
     * @hidden
     * @param iceP_stopId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Stop> _iceI_getStopByIdAsync(int iceP_stopId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Stop> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getStopById", null, sync, _iceE_getStopById);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_stopId);
                 }, istr -> {
                     Stop ret;
                     ret = Stop.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getStopById =
    {
        StopNotFoundException.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RouteServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), RouteServicePrx.class, _RouteServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RouteServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), RouteServicePrx.class, _RouteServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RouteServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), RouteServicePrx.class, _RouteServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RouteServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), RouteServicePrx.class, _RouteServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static RouteServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, RouteServicePrx.class, _RouteServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static RouteServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, RouteServicePrx.class, _RouteServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default RouteServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (RouteServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default RouteServicePrx ice_adapterId(String newAdapterId)
    {
        return (RouteServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default RouteServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (RouteServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default RouteServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (RouteServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default RouteServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (RouteServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default RouteServicePrx ice_connectionCached(boolean newCache)
    {
        return (RouteServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default RouteServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (RouteServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default RouteServicePrx ice_secure(boolean b)
    {
        return (RouteServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default RouteServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (RouteServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default RouteServicePrx ice_preferSecure(boolean b)
    {
        return (RouteServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default RouteServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (RouteServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default RouteServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (RouteServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default RouteServicePrx ice_collocationOptimized(boolean b)
    {
        return (RouteServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default RouteServicePrx ice_twoway()
    {
        return (RouteServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default RouteServicePrx ice_oneway()
    {
        return (RouteServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default RouteServicePrx ice_batchOneway()
    {
        return (RouteServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default RouteServicePrx ice_datagram()
    {
        return (RouteServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default RouteServicePrx ice_batchDatagram()
    {
        return (RouteServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default RouteServicePrx ice_compress(boolean co)
    {
        return (RouteServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default RouteServicePrx ice_timeout(int t)
    {
        return (RouteServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default RouteServicePrx ice_connectionId(String connectionId)
    {
        return (RouteServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default RouteServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (RouteServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Mio::RouteService";
    }
}
