//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Mio;

public class StopNotFoundException extends com.zeroc.Ice.UserException
{
    public StopNotFoundException()
    {
        this.message = "";
    }

    public StopNotFoundException(Throwable cause)
    {
        super(cause);
        this.message = "";
    }

    public StopNotFoundException(int stopId, String message)
    {
        this.stopId = stopId;
        this.message = message;
    }

    public StopNotFoundException(int stopId, String message, Throwable cause)
    {
        super(cause);
        this.stopId = stopId;
        this.message = message;
    }

    public String ice_id()
    {
        return "::Mio::StopNotFoundException";
    }

    public int stopId;

    public String message;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Mio::StopNotFoundException", -1, true);
        ostr_.writeInt(stopId);
        ostr_.writeString(message);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        stopId = istr_.readInt();
        message = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -2665135435424858894L;
}
