//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mioice;

/**
 * Interfaz para los Workers que analizan datagramas
 **/
public interface AnalysisWorker extends com.zeroc.Ice.Object
{
    /**
     * Procesa un archivo de datagramas (o un rango de él)
     * @param filePath Ruta absoluta al archivo de datagramas
     * @param startLine Línea inicial (inclusive)
     * @param endLine Línea final (exclusive), o -1 para hasta el final
     * @param current The Current object for the invocation.
     * @return Lista de estadísticas por arco calculadas en este lote
     **/
    ArcStat[] analyzeDatagrams(String filePath, int startLine, int endLine, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::mioice::AnalysisWorker"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::mioice::AnalysisWorker";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_analyzeDatagrams(AnalysisWorker obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_filePath;
        int iceP_startLine;
        int iceP_endLine;
        iceP_filePath = istr.readString();
        iceP_startLine = istr.readInt();
        iceP_endLine = istr.readInt();
        inS.endReadParams();
        ArcStat[] ret = obj.analyzeDatagrams(iceP_filePath, iceP_startLine, iceP_endLine, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcStatListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "analyzeDatagrams",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_analyzeDatagrams(this, in, current);
            }
            case 1:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
