//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mioice;

/**
 * Resultado del análisis de un lote de datagramas
 **/
public class AnalysisResult implements java.lang.Cloneable,
                                       java.io.Serializable
{
    public int processedDatagrams;

    public double totalDistance;

    public long totalTime;

    public AnalysisResult()
    {
    }

    public AnalysisResult(int processedDatagrams, double totalDistance, long totalTime)
    {
        this.processedDatagrams = processedDatagrams;
        this.totalDistance = totalDistance;
        this.totalTime = totalTime;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        AnalysisResult r = null;
        if(rhs instanceof AnalysisResult)
        {
            r = (AnalysisResult)rhs;
        }

        if(r != null)
        {
            if(this.processedDatagrams != r.processedDatagrams)
            {
                return false;
            }
            if(this.totalDistance != r.totalDistance)
            {
                return false;
            }
            if(this.totalTime != r.totalTime)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::mioice::AnalysisResult");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, processedDatagrams);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalDistance);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalTime);
        return h_;
    }

    public AnalysisResult clone()
    {
        AnalysisResult c = null;
        try
        {
            c = (AnalysisResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.processedDatagrams);
        ostr.writeDouble(this.totalDistance);
        ostr.writeLong(this.totalTime);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.processedDatagrams = istr.readInt();
        this.totalDistance = istr.readDouble();
        this.totalTime = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, AnalysisResult v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public AnalysisResult ice_read(com.zeroc.Ice.InputStream istr)
    {
        AnalysisResult v = new AnalysisResult();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<AnalysisResult> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, AnalysisResult v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(20);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<AnalysisResult> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(AnalysisResult.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final AnalysisResult _nullMarshalValue = new AnalysisResult();

    /** @hidden */
    public static final long serialVersionUID = -8863330914188005515L;
}
