//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mioice;

/**
 * Representa un arco entre dos paradas consecutivas
 **/
public class Arc implements java.lang.Cloneable,
                            java.io.Serializable
{
    public int lineId;

    public String lineName;

    public int orientation;

    public int sequenceNum;

    public Stop fromStop;

    public Stop toStop;

    public double distance;

    public double avgSpeed;

    public Arc()
    {
        this.lineName = "";
        this.fromStop = new Stop();
        this.toStop = new Stop();
    }

    public Arc(int lineId, String lineName, int orientation, int sequenceNum, Stop fromStop, Stop toStop, double distance, double avgSpeed)
    {
        this.lineId = lineId;
        this.lineName = lineName;
        this.orientation = orientation;
        this.sequenceNum = sequenceNum;
        this.fromStop = fromStop;
        this.toStop = toStop;
        this.distance = distance;
        this.avgSpeed = avgSpeed;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Arc r = null;
        if(rhs instanceof Arc)
        {
            r = (Arc)rhs;
        }

        if(r != null)
        {
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.lineName != r.lineName)
            {
                if(this.lineName == null || r.lineName == null || !this.lineName.equals(r.lineName))
                {
                    return false;
                }
            }
            if(this.orientation != r.orientation)
            {
                return false;
            }
            if(this.sequenceNum != r.sequenceNum)
            {
                return false;
            }
            if(this.fromStop != r.fromStop)
            {
                if(this.fromStop == null || r.fromStop == null || !this.fromStop.equals(r.fromStop))
                {
                    return false;
                }
            }
            if(this.toStop != r.toStop)
            {
                if(this.toStop == null || r.toStop == null || !this.toStop.equals(r.toStop))
                {
                    return false;
                }
            }
            if(this.distance != r.distance)
            {
                return false;
            }
            if(this.avgSpeed != r.avgSpeed)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::mioice::Arc");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, orientation);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sequenceNum);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fromStop);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, toStop);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, distance);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, avgSpeed);
        return h_;
    }

    public Arc clone()
    {
        Arc c = null;
        try
        {
            c = (Arc)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.lineId);
        ostr.writeString(this.lineName);
        ostr.writeInt(this.orientation);
        ostr.writeInt(this.sequenceNum);
        Stop.ice_write(ostr, this.fromStop);
        Stop.ice_write(ostr, this.toStop);
        ostr.writeDouble(this.distance);
        ostr.writeDouble(this.avgSpeed);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.lineId = istr.readInt();
        this.lineName = istr.readString();
        this.orientation = istr.readInt();
        this.sequenceNum = istr.readInt();
        this.fromStop = Stop.ice_read(istr);
        this.toStop = Stop.ice_read(istr);
        this.distance = istr.readDouble();
        this.avgSpeed = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Arc v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Arc ice_read(com.zeroc.Ice.InputStream istr)
    {
        Arc v = new Arc();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Arc> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Arc v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Arc> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Arc.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Arc _nullMarshalValue = new Arc();

    /** @hidden */
    public static final long serialVersionUID = 1389317331L;
}
