//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mioice;

/**
 * Helper class for marshaling/unmarshaling ArcStatList.
 **/
public final class ArcStatListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, ArcStat[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                ArcStat.ice_write(ostr, v[i0]);
            }
        }
    }

    public static ArcStat[] read(com.zeroc.Ice.InputStream istr)
    {
        final ArcStat[] v;
        final int len0 = istr.readAndCheckSeqSize(32);
        v = new ArcStat[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = ArcStat.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ArcStat[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, ArcStat[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            final int optSize = v == null ? 0 : v.length;
            ostr.writeSize(optSize > 254 ? optSize * 32 + 5 : optSize * 32 + 1);
            ArcStatListHelper.write(ostr, v);
        }
    }

    public static java.util.Optional<ArcStat[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            ArcStat[] v;
            v = ArcStatListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
