//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mioice;

/**
 * Estructura auxiliar para reportar datos por arco
 **/
public class ArcStat implements java.lang.Cloneable,
                                java.io.Serializable
{
    public int lineId;

    public int orientation;

    public int sequenceNum;

    public double sumDistance;

    public long sumTime;

    public int count;

    public ArcStat()
    {
    }

    public ArcStat(int lineId, int orientation, int sequenceNum, double sumDistance, long sumTime, int count)
    {
        this.lineId = lineId;
        this.orientation = orientation;
        this.sequenceNum = sequenceNum;
        this.sumDistance = sumDistance;
        this.sumTime = sumTime;
        this.count = count;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ArcStat r = null;
        if(rhs instanceof ArcStat)
        {
            r = (ArcStat)rhs;
        }

        if(r != null)
        {
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.orientation != r.orientation)
            {
                return false;
            }
            if(this.sequenceNum != r.sequenceNum)
            {
                return false;
            }
            if(this.sumDistance != r.sumDistance)
            {
                return false;
            }
            if(this.sumTime != r.sumTime)
            {
                return false;
            }
            if(this.count != r.count)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::mioice::ArcStat");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, orientation);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sequenceNum);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sumDistance);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sumTime);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, count);
        return h_;
    }

    public ArcStat clone()
    {
        ArcStat c = null;
        try
        {
            c = (ArcStat)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.lineId);
        ostr.writeInt(this.orientation);
        ostr.writeInt(this.sequenceNum);
        ostr.writeDouble(this.sumDistance);
        ostr.writeLong(this.sumTime);
        ostr.writeInt(this.count);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.lineId = istr.readInt();
        this.orientation = istr.readInt();
        this.sequenceNum = istr.readInt();
        this.sumDistance = istr.readDouble();
        this.sumTime = istr.readLong();
        this.count = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ArcStat v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ArcStat ice_read(com.zeroc.Ice.InputStream istr)
    {
        ArcStat v = new ArcStat();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ArcStat> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ArcStat v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(32);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<ArcStat> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(ArcStat.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ArcStat _nullMarshalValue = new ArcStat();

    /** @hidden */
    public static final long serialVersionUID = -4220389262458134204L;
}
