//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mioice;

/**
 * Servicio para consultar información del grafo completo
 **/
public interface GraphServicePrx extends com.zeroc.Ice.ObjectPrx
{
    /**
     * Obtiene todas las paradas del sistema
     **/
    default Stop[] getAllStops()
    {
        return getAllStops(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene todas las paradas del sistema
     * @param context The Context map to send with the invocation.
     **/
    default Stop[] getAllStops(java.util.Map<String, String> context)
    {
        return _iceI_getAllStopsAsync(context, true).waitForResponse();
    }

    /**
     * Obtiene todas las paradas del sistema
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Stop[]> getAllStopsAsync()
    {
        return _iceI_getAllStopsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene todas las paradas del sistema
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Stop[]> getAllStopsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllStopsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Stop[]> _iceI_getAllStopsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Stop[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAllStops", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Stop[] ret;
                     ret = StopListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Obtiene todos los arcos del sistema
     **/
    default Arc[] getAllArcs()
    {
        return getAllArcs(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene todos los arcos del sistema
     * @param context The Context map to send with the invocation.
     **/
    default Arc[] getAllArcs(java.util.Map<String, String> context)
    {
        return _iceI_getAllArcsAsync(context, true).waitForResponse();
    }

    /**
     * Obtiene todos los arcos del sistema
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Arc[]> getAllArcsAsync()
    {
        return _iceI_getAllArcsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene todos los arcos del sistema
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Arc[]> getAllArcsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllArcsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Arc[]> _iceI_getAllArcsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Arc[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAllArcs", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Arc[] ret;
                     ret = ArcListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Obtiene todos los arcos agrupados por ruta y orientación
     * Retorna un mapa de arcos organizados
     **/
    default Arc[] getArcsByRouteAndOrientation()
    {
        return getArcsByRouteAndOrientation(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene todos los arcos agrupados por ruta y orientación
     * Retorna un mapa de arcos organizados
     * @param context The Context map to send with the invocation.
     **/
    default Arc[] getArcsByRouteAndOrientation(java.util.Map<String, String> context)
    {
        return _iceI_getArcsByRouteAndOrientationAsync(context, true).waitForResponse();
    }

    /**
     * Obtiene todos los arcos agrupados por ruta y orientación
     * Retorna un mapa de arcos organizados
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Arc[]> getArcsByRouteAndOrientationAsync()
    {
        return _iceI_getArcsByRouteAndOrientationAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene todos los arcos agrupados por ruta y orientación
     * Retorna un mapa de arcos organizados
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<Arc[]> getArcsByRouteAndOrientationAsync(java.util.Map<String, String> context)
    {
        return _iceI_getArcsByRouteAndOrientationAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Arc[]> _iceI_getArcsByRouteAndOrientationAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Arc[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getArcsByRouteAndOrientation", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Arc[] ret;
                     ret = ArcListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Obtiene estadísticas del grafo
     * Retorna: [numRoutes, numStops, numArcs, numArcsOrientation0, numArcsOrientation1]
     **/
    default int[] getGraphStatistics()
    {
        return getGraphStatistics(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene estadísticas del grafo
     * Retorna: [numRoutes, numStops, numArcs, numArcsOrientation0, numArcsOrientation1]
     * @param context The Context map to send with the invocation.
     **/
    default int[] getGraphStatistics(java.util.Map<String, String> context)
    {
        return _iceI_getGraphStatisticsAsync(context, true).waitForResponse();
    }

    /**
     * Obtiene estadísticas del grafo
     * Retorna: [numRoutes, numStops, numArcs, numArcsOrientation0, numArcsOrientation1]
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<int[]> getGraphStatisticsAsync()
    {
        return _iceI_getGraphStatisticsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene estadísticas del grafo
     * Retorna: [numRoutes, numStops, numArcs, numArcsOrientation0, numArcsOrientation1]
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<int[]> getGraphStatisticsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getGraphStatisticsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<int[]> _iceI_getGraphStatisticsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<int[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getGraphStatistics", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int[] ret;
                     ret = istr.readIntSeq();
                     return ret;
                 });
        return f;
    }

    /**
     * Imprime en consola del servidor el listado completo de arcos
     * organizados por ruta y orientación
     **/
    default void printArcsToConsole()
    {
        printArcsToConsole(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Imprime en consola del servidor el listado completo de arcos
     * organizados por ruta y orientación
     * @param context The Context map to send with the invocation.
     **/
    default void printArcsToConsole(java.util.Map<String, String> context)
    {
        _iceI_printArcsToConsoleAsync(context, true).waitForResponse();
    }

    /**
     * Imprime en consola del servidor el listado completo de arcos
     * organizados por ruta y orientación
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> printArcsToConsoleAsync()
    {
        return _iceI_printArcsToConsoleAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Imprime en consola del servidor el listado completo de arcos
     * organizados por ruta y orientación
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> printArcsToConsoleAsync(java.util.Map<String, String> context)
    {
        return _iceI_printArcsToConsoleAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_printArcsToConsoleAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "printArcsToConsole", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    /**
     * Encuentra la ruta más corta entre dos paradas
     * @param originStopId ID de la parada de origen
     * @param destStopId ID de la parada de destino
     * @return RouteResult con la ruta encontrada o información de error
     **/
    default RouteResult findRoute(int originStopId, int destStopId)
        throws StopNotFoundException
    {
        return findRoute(originStopId, destStopId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Encuentra la ruta más corta entre dos paradas
     * @param originStopId ID de la parada de origen
     * @param destStopId ID de la parada de destino
     * @param context The Context map to send with the invocation.
     * @return RouteResult con la ruta encontrada o información de error
     **/
    default RouteResult findRoute(int originStopId, int destStopId, java.util.Map<String, String> context)
        throws StopNotFoundException
    {
        try
        {
            return _iceI_findRouteAsync(originStopId, destStopId, context, true).waitForResponseOrUserEx();
        }
        catch(StopNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    /**
     * Encuentra la ruta más corta entre dos paradas
     * @param originStopId ID de la parada de origen
     * @param destStopId ID de la parada de destino
     * @return RouteResult con la ruta encontrada o información de error
     **/
    default java.util.concurrent.CompletableFuture<RouteResult> findRouteAsync(int originStopId, int destStopId)
    {
        return _iceI_findRouteAsync(originStopId, destStopId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Encuentra la ruta más corta entre dos paradas
     * @param originStopId ID de la parada de origen
     * @param destStopId ID de la parada de destino
     * @param context The Context map to send with the invocation.
     * @return RouteResult con la ruta encontrada o información de error
     **/
    default java.util.concurrent.CompletableFuture<RouteResult> findRouteAsync(int originStopId, int destStopId, java.util.Map<String, String> context)
    {
        return _iceI_findRouteAsync(originStopId, destStopId, context, false);
    }

    /**
     * @hidden
     * @param iceP_originStopId -
     * @param iceP_destStopId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<RouteResult> _iceI_findRouteAsync(int iceP_originStopId, int iceP_destStopId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<RouteResult> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "findRoute", null, sync, _iceE_findRoute);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_originStopId);
                     ostr.writeInt(iceP_destStopId);
                 }, istr -> {
                     RouteResult ret;
                     ret = RouteResult.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_findRoute =
    {
        StopNotFoundException.class
    };

    /**
     * Obtiene todas las paradas alcanzables desde una parada de origen
     * @param originStopId ID de la parada de origen
     * @return IntList con los IDs de las paradas alcanzables
     **/
    default int[] getReachableStops(int originStopId)
        throws StopNotFoundException
    {
        return getReachableStops(originStopId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene todas las paradas alcanzables desde una parada de origen
     * @param originStopId ID de la parada de origen
     * @param context The Context map to send with the invocation.
     * @return IntList con los IDs de las paradas alcanzables
     **/
    default int[] getReachableStops(int originStopId, java.util.Map<String, String> context)
        throws StopNotFoundException
    {
        try
        {
            return _iceI_getReachableStopsAsync(originStopId, context, true).waitForResponseOrUserEx();
        }
        catch(StopNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    /**
     * Obtiene todas las paradas alcanzables desde una parada de origen
     * @param originStopId ID de la parada de origen
     * @return IntList con los IDs de las paradas alcanzables
     **/
    default java.util.concurrent.CompletableFuture<int[]> getReachableStopsAsync(int originStopId)
    {
        return _iceI_getReachableStopsAsync(originStopId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene todas las paradas alcanzables desde una parada de origen
     * @param originStopId ID de la parada de origen
     * @param context The Context map to send with the invocation.
     * @return IntList con los IDs de las paradas alcanzables
     **/
    default java.util.concurrent.CompletableFuture<int[]> getReachableStopsAsync(int originStopId, java.util.Map<String, String> context)
    {
        return _iceI_getReachableStopsAsync(originStopId, context, false);
    }

    /**
     * @hidden
     * @param iceP_originStopId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<int[]> _iceI_getReachableStopsAsync(int iceP_originStopId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<int[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getReachableStops", null, sync, _iceE_getReachableStops);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_originStopId);
                 }, istr -> {
                     int[] ret;
                     ret = istr.readIntSeq();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getReachableStops =
    {
        StopNotFoundException.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static GraphServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), GraphServicePrx.class, _GraphServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static GraphServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), GraphServicePrx.class, _GraphServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static GraphServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), GraphServicePrx.class, _GraphServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static GraphServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), GraphServicePrx.class, _GraphServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static GraphServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, GraphServicePrx.class, _GraphServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static GraphServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, GraphServicePrx.class, _GraphServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default GraphServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (GraphServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default GraphServicePrx ice_adapterId(String newAdapterId)
    {
        return (GraphServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default GraphServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (GraphServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default GraphServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (GraphServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default GraphServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (GraphServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default GraphServicePrx ice_connectionCached(boolean newCache)
    {
        return (GraphServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default GraphServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (GraphServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default GraphServicePrx ice_secure(boolean b)
    {
        return (GraphServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default GraphServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (GraphServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default GraphServicePrx ice_preferSecure(boolean b)
    {
        return (GraphServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default GraphServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (GraphServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default GraphServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (GraphServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default GraphServicePrx ice_collocationOptimized(boolean b)
    {
        return (GraphServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default GraphServicePrx ice_twoway()
    {
        return (GraphServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default GraphServicePrx ice_oneway()
    {
        return (GraphServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default GraphServicePrx ice_batchOneway()
    {
        return (GraphServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default GraphServicePrx ice_datagram()
    {
        return (GraphServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default GraphServicePrx ice_batchDatagram()
    {
        return (GraphServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default GraphServicePrx ice_compress(boolean co)
    {
        return (GraphServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default GraphServicePrx ice_timeout(int t)
    {
        return (GraphServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default GraphServicePrx ice_connectionId(String connectionId)
    {
        return (GraphServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default GraphServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (GraphServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::mioice::GraphService";
    }
}
