//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mioice;

public class InvalidOrientationException extends com.zeroc.Ice.UserException
{
    public InvalidOrientationException()
    {
        this.message = "";
    }

    public InvalidOrientationException(Throwable cause)
    {
        super(cause);
        this.message = "";
    }

    public InvalidOrientationException(int orientation, String message)
    {
        this.orientation = orientation;
        this.message = message;
    }

    public InvalidOrientationException(int orientation, String message, Throwable cause)
    {
        super(cause);
        this.orientation = orientation;
        this.message = message;
    }

    public String ice_id()
    {
        return "::mioice::InvalidOrientationException";
    }

    public int orientation;

    public String message;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::mioice::InvalidOrientationException", -1, true);
        ostr_.writeInt(orientation);
        ostr_.writeString(message);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        orientation = istr_.readInt();
        message = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 1271522319989064034L;
}
