//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mioice;

/**
 * Representa una ruta del sistema MIO
 **/
public class Line implements java.lang.Cloneable,
                             java.io.Serializable
{
    public int lineId;

    public int planVersionId;

    public String shortName;

    public String description;

    public String activationDate;

    public Line()
    {
        this.shortName = "";
        this.description = "";
        this.activationDate = "";
    }

    public Line(int lineId, int planVersionId, String shortName, String description, String activationDate)
    {
        this.lineId = lineId;
        this.planVersionId = planVersionId;
        this.shortName = shortName;
        this.description = description;
        this.activationDate = activationDate;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Line r = null;
        if(rhs instanceof Line)
        {
            r = (Line)rhs;
        }

        if(r != null)
        {
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.planVersionId != r.planVersionId)
            {
                return false;
            }
            if(this.shortName != r.shortName)
            {
                if(this.shortName == null || r.shortName == null || !this.shortName.equals(r.shortName))
                {
                    return false;
                }
            }
            if(this.description != r.description)
            {
                if(this.description == null || r.description == null || !this.description.equals(r.description))
                {
                    return false;
                }
            }
            if(this.activationDate != r.activationDate)
            {
                if(this.activationDate == null || r.activationDate == null || !this.activationDate.equals(r.activationDate))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::mioice::Line");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, planVersionId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, shortName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, description);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, activationDate);
        return h_;
    }

    public Line clone()
    {
        Line c = null;
        try
        {
            c = (Line)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.lineId);
        ostr.writeInt(this.planVersionId);
        ostr.writeString(this.shortName);
        ostr.writeString(this.description);
        ostr.writeString(this.activationDate);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.lineId = istr.readInt();
        this.planVersionId = istr.readInt();
        this.shortName = istr.readString();
        this.description = istr.readString();
        this.activationDate = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Line v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Line ice_read(com.zeroc.Ice.InputStream istr)
    {
        Line v = new Line();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Line> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Line v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Line> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Line.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Line _nullMarshalValue = new Line();

    /** @hidden */
    public static final long serialVersionUID = -2103237550L;
}
