//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mioice;

/**
 * Representa una ruta calculada entre dos paradas
 **/
public class RouteResult implements java.lang.Cloneable,
                                    java.io.Serializable
{
    public boolean found;

    public Stop[] stops;

    public Arc[] arcs;

    public double totalDistance;

    public double estimatedTime;

    public int numTransfers;

    public String message;

    public RouteResult()
    {
        this.message = "";
    }

    public RouteResult(boolean found, Stop[] stops, Arc[] arcs, double totalDistance, double estimatedTime, int numTransfers, String message)
    {
        this.found = found;
        this.stops = stops;
        this.arcs = arcs;
        this.totalDistance = totalDistance;
        this.estimatedTime = estimatedTime;
        this.numTransfers = numTransfers;
        this.message = message;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        RouteResult r = null;
        if(rhs instanceof RouteResult)
        {
            r = (RouteResult)rhs;
        }

        if(r != null)
        {
            if(this.found != r.found)
            {
                return false;
            }
            if(!java.util.Arrays.equals(this.stops, r.stops))
            {
                return false;
            }
            if(!java.util.Arrays.equals(this.arcs, r.arcs))
            {
                return false;
            }
            if(this.totalDistance != r.totalDistance)
            {
                return false;
            }
            if(this.estimatedTime != r.estimatedTime)
            {
                return false;
            }
            if(this.numTransfers != r.numTransfers)
            {
                return false;
            }
            if(this.message != r.message)
            {
                if(this.message == null || r.message == null || !this.message.equals(r.message))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::mioice::RouteResult");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, found);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stops);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, arcs);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalDistance);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, estimatedTime);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, numTransfers);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, message);
        return h_;
    }

    public RouteResult clone()
    {
        RouteResult c = null;
        try
        {
            c = (RouteResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeBool(this.found);
        StopListHelper.write(ostr, this.stops);
        ArcListHelper.write(ostr, this.arcs);
        ostr.writeDouble(this.totalDistance);
        ostr.writeDouble(this.estimatedTime);
        ostr.writeInt(this.numTransfers);
        ostr.writeString(this.message);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.found = istr.readBool();
        this.stops = StopListHelper.read(istr);
        this.arcs = ArcListHelper.read(istr);
        this.totalDistance = istr.readDouble();
        this.estimatedTime = istr.readDouble();
        this.numTransfers = istr.readInt();
        this.message = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, RouteResult v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public RouteResult ice_read(com.zeroc.Ice.InputStream istr)
    {
        RouteResult v = new RouteResult();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<RouteResult> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, RouteResult v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<RouteResult> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(RouteResult.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final RouteResult _nullMarshalValue = new RouteResult();

    /** @hidden */
    public static final long serialVersionUID = -7235408184787576475L;
}
