//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MioGraph.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mioice;

/**
 * Servicio para consultar información de rutas
 **/
public interface RouteService extends com.zeroc.Ice.Object
{
    /**
     * Obtiene todas las rutas disponibles
     * @param current The Current object for the invocation.
     **/
    Line[] getAllLines(com.zeroc.Ice.Current current);

    /**
     * Obtiene una ruta específica por ID
     * @param current The Current object for the invocation.
     **/
    Line getLineById(int lineId, com.zeroc.Ice.Current current)
        throws LineNotFoundException;

    /**
     * Obtiene todas las paradas de una ruta específica
     * @param lineId ID de la ruta
     * @param orientation 0=ida, 1=regreso
     * @param current The Current object for the invocation.
     **/
    Stop[] getStopsByLine(int lineId, int orientation, com.zeroc.Ice.Current current)
        throws InvalidOrientationException,
               LineNotFoundException;

    /**
     * Obtiene los arcos de una ruta específica
     * @param lineId ID de la ruta
     * @param orientation 0=ida, 1=regreso
     * @param current The Current object for the invocation.
     **/
    Arc[] getArcsByLine(int lineId, int orientation, com.zeroc.Ice.Current current)
        throws InvalidOrientationException,
               LineNotFoundException;

    /**
     * Obtiene información de una parada específica
     * @param current The Current object for the invocation.
     **/
    Stop getStopById(int stopId, com.zeroc.Ice.Current current)
        throws StopNotFoundException;

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::mioice::RouteService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::mioice::RouteService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAllLines(RouteService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        Line[] ret = obj.getAllLines(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        LineListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getLineById(RouteService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_lineId;
        iceP_lineId = istr.readInt();
        inS.endReadParams();
        Line ret = obj.getLineById(iceP_lineId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Line.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getStopsByLine(RouteService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_lineId;
        int iceP_orientation;
        iceP_lineId = istr.readInt();
        iceP_orientation = istr.readInt();
        inS.endReadParams();
        Stop[] ret = obj.getStopsByLine(iceP_lineId, iceP_orientation, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        StopListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getArcsByLine(RouteService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_lineId;
        int iceP_orientation;
        iceP_lineId = istr.readInt();
        iceP_orientation = istr.readInt();
        inS.endReadParams();
        Arc[] ret = obj.getArcsByLine(iceP_lineId, iceP_orientation, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getStopById(RouteService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_stopId;
        iceP_stopId = istr.readInt();
        inS.endReadParams();
        Stop ret = obj.getStopById(iceP_stopId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Stop.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "getAllLines",
        "getArcsByLine",
        "getLineById",
        "getStopById",
        "getStopsByLine",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_getAllLines(this, in, current);
            }
            case 1:
            {
                return _iceD_getArcsByLine(this, in, current);
            }
            case 2:
            {
                return _iceD_getLineById(this, in, current);
            }
            case 3:
            {
                return _iceD_getStopById(this, in, current);
            }
            case 4:
            {
                return _iceD_getStopsByLine(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
